### ISSUE TITLE
png_retina() not behaving same as png() with purrr:iwalk()

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/envreportutils#19]
Exploring why `png_retina` is not working with `purrr` function &mdash; see gist [here](https://gist.github.com/stephhazlitt/cef14d7dcc5a72648cd18b45eb61b7bd). 

Both `ggsave()` & `png()` work with `purrr::iwalk()`, however `emvreportutils::png_retina()` throws an error (`Error in paste0(.y, "_retina.png") : object '.y' not found`).

**Comment by ateucher** [comment]
To round out the testing, [same results using `lapply` in place of `purrr` functions](https://gist.github.com/stephhazlitt/cef14d7dcc5a72648cd18b45eb61b7bd#gistcomment-2650419)
