### ISSUE TITLE
Investigate dropping ggthemes dependency

### ISSUE THREAD

**Issue by ateucher** [bcgov/envreportutils#5]
For `theme_soe`, could start with `ggplot2::theme_bw` and use `%+replace%` to get theme modifications we want.

**Comment by ateucher** [comment]
http://docs.ggplot2.org/current/vignettes/extending-ggplot2.html
and
http://docs.ggplot2.org/dev/vignettes/themes.html

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancements](https://trello.com/c/Nhm40VR1/5-enhancements)

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rejig envreportutils into 2 packages](https://trello.com/c/MjjTm9SZ/33-rejig-envreportutils-into-2-packages)

**Comment by stephhazlitt** [comment]
Updated url: http://ggplot2.tidyverse.org/articles/extending-ggplot2.html

**Comment by stephhazlitt** [comment]
Closed by https://github.com/bcgov/envreportutils/commit/59f3ade686a710c6f6c879408322f25cca11292e.
