### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ateucher** [bcgov/envreportutils#8]
There are several new functions in the package that aren't highlighted in the README. Especially the RStudio Addins.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation](https://trello.com/c/yfZpal2m/6-documentation)

**Comment by stephhazlitt** [comment]
Closed in de075daf3c8c2046808e31bfd96f4d39f5825530
