### ISSUE TITLE
Use 'usethis' package

### ISSUE THREAD

**Issue by ateucher** [bcgov/envreportutils#9]
For functions like`add_code_of_conduct`, `add_contributing` etc., [usethis](https://github.com/r-lib/usethis) likely has more robust implementations than we have - should import **usethis** when it hits CRAN.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancements](https://trello.com/c/Nhm40VR1/5-enhancements)

**Comment by ateucher** [comment]
Closing - opened the same issue in the [new repo](https://github.com/bcgov/bcgovr)
